pipeline {
    agent any
    stages {
        stage('Clone') {
            steps {
                git 'https://github.com/CliberCastillo/simple-java.git'
            }
        }
        stage('list') {
            steps {
                sh 'ls'
            }
        }
        stage('Containers'){
            steps {
                sh 'docker ps'
            }
        }
    }
}