pipeline {
    agent none

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'maven:3-openjdk-11'
                    args '-v /root/.m2:/root/.m2'
                }
            }
            steps {
                git 'https://github.com/CliberCastillo/simple-java.git'
                sh 'mvn clean install'
            }
        }
        stage('Build Docker Image') {
            agent any
            steps {
                sh 'docker build -t clibercastillo/simple-java:latest .'
            }
        }
        stage('Push to Docker Hub') {
            agent any
            steps {
                sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
                sh 'docker push clibercastillo/simple-java:latest'
            }
        }
    }
}