pipeline {
    agent any
    stages {
        stage('Clonar el repositorio') {
            steps {
                git 'https://github.com/CliberCastillo/simple-java.git'
            }
        }
        stage('Mostrar mensaje'){
            steps {
                echo 'Mensaje de ejemplo'
            }
        }
    }
}
